// frontend/src/app/components/Layout.tsx
import { Outlet, Link, useLocation } from 'react-router-dom'
import { Menu, X, Wallet, Zap, Github } from 'lucide-react'
import { useState, useEffect } from 'react'
import { useWallet } from '../../hooks/useWallet'
import { Button } from './Button'
import { cn, shortenAddress } from '../../lib/utils'
import WalletModal from './WalletModal'

export default function Layout() {
  const location = useLocation()
  const { address, isConnected, isAuthenticated, tier, connect, signIn, signOut } = useWallet()
  const [menuOpen, setMenuOpen] = useState(false)
  const [showWalletModal, setShowWalletModal] = useState(false)

  const handleConnectWallet = () => {
    setShowWalletModal(true)
  }

  // Efeito para mostrar modal quando conectar wallet mas não estiver autenticado
  useEffect(() => {
    if (isConnected && !isAuthenticated && address) {
      setShowWalletModal(true)
    }
  }, [isConnected, isAuthenticated, address])

  const handleSignIn = async () => {
    try {
      await signIn()
      setShowWalletModal(false)
    } catch (error) {
      console.error('Sign in error:', error)
    }
  }

  const isActive = (path: string) => location.pathname === path

  return (
    <div className="min-h-screen bg-[#0B0B0B] text-[#F7F7F8]">
      {/* Wallet Connect Modal */}
      <WalletModal
        isOpen={showWalletModal}
        onClose={() => setShowWalletModal(false)}
        onConnect={connect}
        onSignIn={isConnected && !isAuthenticated ? handleSignIn : undefined}
        isConnected={isConnected}
        isAuthenticated={isAuthenticated}
      />

      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-[#0B0B0B] border-b border-[rgba(255,255,255,0.1)] h-16">
        <div className="container mx-auto px-6 h-full flex items-center justify-between">
          {/* Logo */}
          <div className="flex items-center gap-8">
            <Link to="/" className="flex items-center gap-2">
              <Zap className="w-6 h-6 text-[#FF6A00]" />
              <h1 className="font-mono font-bold text-xl">SNE Radar</h1>
            </Link>
            
            {/* Desktop Nav */}
            <div className="hidden md:flex items-center gap-6">
              <Link
                to="/dashboard"
                className={cn(
                  'text-sm transition-colors',
                  isActive('/dashboard') || isActive('/')
                    ? 'text-[#F7F7F8] border-b-2 border-[#FF6A00] pb-0.5'
                    : 'text-[#A6A6A6] hover:text-[#F7F7F8]'
                )}
              >
                Dashboard
              </Link>
              <Link
                to="/chart"
                className={cn(
                  'text-sm transition-colors',
                  isActive('/chart')
                    ? 'text-[#F7F7F8] border-b-2 border-[#FF6A00] pb-0.5'
                    : 'text-[#A6A6A6] hover:text-[#F7F7F8]'
                )}
              >
                Charts
              </Link>
              <Link
                to="/analysis"
                className={cn(
                  'text-sm transition-colors',
                  isActive('/analysis')
                    ? 'text-[#F7F7F8] border-b-2 border-[#FF6A00] pb-0.5'
                    : 'text-[#A6A6A6] hover:text-[#F7F7F8]'
                )}
              >
                Analysis
              </Link>
            </div>
          </div>

          {/* Right Side */}
          <div className="flex items-center gap-4">
            {/* Tier Badge & Wallet - Só mostrar quando AUTENTICADO */}
            {isAuthenticated && address ? (
              <div className="hidden md:flex items-center gap-3">
                <Link
                  to="/pricing"
                  className={cn(
                    'px-3 py-1 rounded-full text-xs font-mono font-medium transition-all hover:scale-105',
                    tier === 'free' && 'bg-[#1B1B1F] text-[#A6A6A6] hover:bg-[#252529]',
                    tier === 'premium' && 'bg-[rgba(255,106,0,0.2)] text-[#FF6A00] hover:bg-[rgba(255,106,0,0.3)]',
                    tier === 'pro' && 'bg-[rgba(255,200,87,0.2)] text-[#FFC857] hover:bg-[rgba(255,200,87,0.3)]'
                  )}
                >
                  {tier.toUpperCase()}
                </Link>
                <span className="font-mono text-sm text-[#A6A6A6]">
                  {shortenAddress(address)}
                </span>
                <button
                  onClick={signOut}
                  className="text-sm text-[#A6A6A6] hover:text-[#FF4D4F] transition-colors"
                >
                  Sair
                </button>
              </div>
            ) : (
              <Button onClick={handleConnectWallet} size="sm" disabled={isConnected && !isAuthenticated}>
                <Wallet className="w-4 h-4 mr-2 inline" />
                {isConnected ? 'Assinar Mensagem' : 'Conectar Carteira'}
              </Button>
            )}

            <a
              href="https://github.com/SNE-Labs"
              target="_blank"
              rel="noopener noreferrer"
              className="hidden md:block p-2 rounded transition-colors hover:bg-[#1B1B1F]"
              aria-label="GitHub"
            >
              <Github className="w-5 h-5 text-[#A6A6A6]" />
            </a>

            {/* Mobile Menu Toggle */}
            <button
              className="md:hidden p-2"
              onClick={() => setMenuOpen(!menuOpen)}
              aria-label="Toggle menu"
            >
              {menuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {menuOpen && (
          <div className="md:hidden bg-[#111216] border-t border-[rgba(255,255,255,0.1)] p-4">
            <div className="flex flex-col gap-3">
              <Link
                to="/dashboard"
                onClick={() => setMenuOpen(false)}
                className="text-left py-2"
              >
                Dashboard
              </Link>
              <Link
                to="/chart"
                onClick={() => setMenuOpen(false)}
                className="text-left py-2"
              >
                Charts
              </Link>
              <Link
                to="/analysis"
                onClick={() => setMenuOpen(false)}
                className="text-left py-2"
              >
                Analysis
              </Link>
              <Link
                to="/pricing"
                onClick={() => setMenuOpen(false)}
                className="text-left py-2"
              >
                Pricing
              </Link>
            </div>
          </div>
        )}
      </nav>

      {/* Main Content */}
      <main className="container mx-auto px-6 py-8">
        <Outlet />
      </main>

      {/* Footer */}
      <footer className="border-t border-[rgba(255,255,255,0.1)] mt-auto py-12 px-6 bg-[#111216]">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <span className="font-mono font-bold text-xl">SNE Radar</span>
              </div>
              <p className="text-sm text-[#A6A6A6]">
                Análise técnica avançada com IA e execução verificável
              </p>
            </div>

            <div>
              <h4 className="mb-3 font-semibold">Produtos</h4>
              <ul className="space-y-2 text-sm text-[#A6A6A6]">
                <li><a href="https://radar.snelabs.space" className="hover:text-[#FF6A00] transition-colors">SNE Radar</a></li>
                <li><a href="https://snelabs.space" className="hover:text-[#FF6A00] transition-colors">SNE Vault</a></li>
                <li><a href="https://pass.snelabs.space" className="hover:text-[#FF6A00] transition-colors">SNE Pass</a></li>
              </ul>
            </div>

            <div>
              <h4 className="mb-3 font-semibold">Recursos</h4>
              <ul className="space-y-2 text-sm text-[#A6A6A6]">
                <li><Link to="/dashboard" className="hover:text-[#FF6A00] transition-colors">Dashboard</Link></li>
                <li><Link to="/chart" className="hover:text-[#FF6A00] transition-colors">Gráficos</Link></li>
                <li><Link to="/analysis" className="hover:text-[#FF6A00] transition-colors">Análise</Link></li>
              </ul>
            </div>

            <div>
              <h4 className="mb-3 font-semibold">Legal</h4>
              <ul className="space-y-2 text-sm text-[#A6A6A6]">
                <li><a href="#" className="hover:text-[#FF6A00] transition-colors">Licenças</a></li>
                <li><a href="#" className="hover:text-[#FF6A00] transition-colors">Security</a></li>
              </ul>
            </div>
          </div>

          <div className="pt-6 border-t border-[rgba(255,255,255,0.1)]">
            <p className="text-sm text-[#A6A6A6]">
              © {new Date().getFullYear()} SNE Labs. Licença MIT. Sistema operando em Scroll L2.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

// frontend/src/components/Layout.vue
<template>
  <div class="layout min-h-screen bg-sne">
    <!-- Navigation -->
    <nav
      role="navigation"
      aria-label="Main navigation"
      class="fixed top-0 left-0 right-0 z-50 border-b"
      style="background-color: var(--sne-bg); border-color: var(--border)"
    >
      <div class="max-w-[1440px] mx-auto px-6 lg:px-24">
        <div class="flex items-center justify-between h-16">
          <!-- Brand -->
          <router-link
            to="/"
            class="flex items-center gap-2 group"
            aria-label="SNE Radar - Home"
          >
            <span
              class="font-mono tracking-tight transition-colors"
              style="color: var(--sne-text-primary); font-weight: 700; font-size: 1rem"
            >
              SNE Radar
            </span>
          </router-link>

          <!-- Desktop Navigation -->
          <div class="hidden md:flex items-center gap-1">
            <router-link
              to="/dashboard"
              class="px-4 py-2 rounded transition-all duration-150 flex items-center gap-2 focus:outline-none focus:ring-2 focus:ring-offset-2"
              style="color: var(--sne-text-secondary)"
              active-class="text-accent"
            >
              Dashboard
            </router-link>
            <router-link
              to="/chart"
              class="px-4 py-2 rounded transition-all duration-150 flex items-center gap-2 focus:outline-none focus:ring-2 focus:ring-offset-2"
              style="color: var(--sne-text-secondary)"
              active-class="text-accent"
            >
              Charts
            </router-link>
            <router-link
              to="/analysis"
              class="px-4 py-2 rounded transition-all duration-150 flex items-center gap-2 focus:outline-none focus:ring-2 focus:ring-offset-2"
              style="color: var(--sne-text-secondary)"
              active-class="text-accent"
            >
              Analysis
            </router-link>
          </div>

          <!-- Actions -->
          <div class="hidden md:flex items-center gap-3">
            <a
              href="https://github.com/SNE-Labs"
              target="_blank"
              rel="noopener noreferrer"
              class="p-2 rounded transition-colors"
              style="color: var(--sne-text-secondary)"
              aria-label="GitHub"
            >
              <Github class="w-5 h-5" />
            </a>

            <button
              v-if="!isConnected"
              @click="connectWallet"
              class="btn-primary px-4 py-2"
            >
              Conectar Carteira
            </button>
            <div v-else class="flex items-center gap-3">
              <div class="text-right">
                <div class="text-xs font-mono" style="color: var(--sne-text-secondary)">Tier</div>
                <div class="text-sm font-mono uppercase" style="color: var(--sne-accent)">{{ tier }}</div>
              </div>
              <div
                class="w-8 h-8 rounded-full border flex items-center justify-center"
                style="border-color: var(--sne-accent)"
              >
                <span class="text-xs font-mono text-accent">
                  {{ address?.slice(0, 4) }}...{{ address?.slice(-4) }}
                </span>
              </div>
            </div>
          </div>

          <!-- Mobile Toggle -->
          <button
            class="md:hidden p-2"
            @click="mobileOpen = !mobileOpen"
            :aria-expanded="mobileOpen"
            aria-controls="sne-mobile-menu"
            :aria-label="mobileOpen ? 'Fechar menu' : 'Abrir menu'"
            style="color: var(--sne-text-primary)"
          >
            <Menu v-if="!mobileOpen" class="w-6 h-6" />
            <X v-else class="w-6 h-6" />
          </button>
        </div>

        <!-- Mobile Menu -->
        <div
          v-if="mobileOpen"
          id="sne-mobile-menu"
          class="md:hidden py-4 border-t"
          style="border-color: var(--border)"
        >
          <router-link
            to="/dashboard"
            @click="mobileOpen = false"
            class="flex items-center gap-2 px-4 py-3 transition-colors"
            style="color: var(--sne-text-secondary)"
          >
            Dashboard
          </router-link>
          <router-link
            to="/chart"
            @click="mobileOpen = false"
            class="flex items-center gap-2 px-4 py-3 transition-colors"
            style="color: var(--sne-text-secondary)"
          >
            Charts
          </router-link>
          <router-link
            to="/analysis"
            @click="mobileOpen = false"
            class="flex items-center gap-2 px-4 py-3 transition-colors"
            style="color: var(--sne-text-secondary)"
          >
            Analysis
          </router-link>
          <div class="mt-4 px-4">
            <button
              v-if="!isConnected"
              @click="connectWallet(); mobileOpen = false"
              class="btn-primary w-full px-4 py-2"
            >
              Conectar Carteira
            </button>
            <div v-else class="text-sm" style="color: var(--sne-text-secondary)">
              {{ address?.slice(0, 6) }}...{{ address?.slice(-4) }}
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- Main Content (with padding for fixed nav) -->
    <main class="pt-16">
      <slot />
    </main>

    <!-- Footer -->
    <footer
      class="py-12 px-6 lg:px-24 border-t mt-auto"
      style="border-color: var(--border); background-color: var(--sne-surface-1)"
    >
      <div class="max-w-[1200px] mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          <div>
            <div class="flex items-center gap-2 mb-4">
              <span
                class="font-mono"
                style="color: var(--sne-text-primary); font-weight: 700"
              >
                SNE Radar
              </span>
            </div>
            <p style="font-size: var(--text-small); color: var(--sne-text-secondary)">
              Análise técnica avançada com IA e execução verificável
            </p>
          </div>

          <div>
            <h4 class="mb-3" style="color: var(--sne-text-primary)">Produtos</h4>
            <ul class="space-y-2" style="font-size: var(--text-body)">
              <li>
                <a href="https://radar.snelabs.space" style="color: var(--sne-text-secondary)">
                  SNE Radar
                </a>
              </li>
              <li>
                <a href="https://snelabs.space" style="color: var(--sne-text-secondary)">
                  SNE Vault
                </a>
              </li>
              <li>
                <a href="https://pass.snelabs.space" style="color: var(--sne-text-secondary)">
                  SNE Pass
                </a>
              </li>
            </ul>
          </div>

          <div>
            <h4 class="mb-3" style="color: var(--sne-text-primary)">Recursos</h4>
            <ul class="space-y-2" style="font-size: var(--text-body)">
              <li>
                <router-link to="/dashboard" style="color: var(--sne-text-secondary)">
                  Dashboard
                </router-link>
              </li>
              <li>
                <router-link to="/chart" style="color: var(--sne-text-secondary)">
                  Gráficos
                </router-link>
              </li>
              <li>
                <router-link to="/analysis" style="color: var(--sne-text-secondary)">
                  Análise
                </router-link>
              </li>
            </ul>
          </div>

          <div>
            <h4 class="mb-3" style="color: var(--sne-text-primary)">Legal</h4>
            <ul class="space-y-2" style="font-size: var(--text-body)">
              <li>
                <a href="#" style="color: var(--sne-text-secondary)">
                  Licenças
                </a>
              </li>
              <li>
                <a href="#" style="color: var(--sne-text-secondary)">
                  Security
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div class="pt-6 border-t" style="border-color: var(--border)">
          <p style="font-size: var(--text-small); color: var(--sne-text-secondary)">
            © {{ currentYear }} SNE Labs. Licença MIT. Sistema operando em Scroll L2.
          </p>
        </div>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Menu, X, Github } from 'lucide-vue-next'

// Estado do wallet com valores padrão seguros
const address = ref<string | null>(null)
const isConnected = ref(false)
const tier = ref<'free' | 'premium' | 'pro'>('free')
const mobileOpen = ref(false)

const currentYear = new Date().getFullYear()

// Função de conexão segura
const connectWallet = async () => {
  try {
    // Importar dinamicamente para evitar erro em SSR
    const { useWallet } = await import('@/composables/useWallet')
    const wallet = useWallet()
    await wallet.connectWallet()
    address.value = wallet.address.value
    isConnected.value = wallet.isConnected.value
    tier.value = wallet.tier.value
  } catch (err) {
    console.error('Failed to connect wallet:', err)
  }
}

// Tentar carregar estado do wallet se disponível
onMounted(() => {
  if (typeof window !== 'undefined') {
    import('@/composables/useWallet')
      .then(({ useWallet }) => {
        const wallet = useWallet()
        address.value = wallet.address.value
        isConnected.value = wallet.isConnected.value
        tier.value = wallet.tier.value
      })
      .catch((err) => {
        console.warn('Wallet not available:', err)
        // Continuar sem wallet
      })
  }
})
</script>

<style scoped>
.bg-sne {
  background: var(--sne-bg);
}

.router-link-active {
  color: var(--sne-accent) !important;
}
</style>
