// frontend/src/components/Layout.vue
<template>
  <div class="layout min-h-screen bg-terminal-bg">
    <!-- Header -->
    <header class="border-b border-terminal-border bg-dark-card/50 backdrop-blur-sm sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-6 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-6">
            <router-link to="/" class="flex items-center gap-3">
              <div class="w-10 h-10 border-2 border-terminal-accent rounded flex items-center justify-center">
                <span class="text-terminal-accent font-mono font-bold text-xl">SNE</span>
              </div>
              <div>
                <h1 class="text-xl font-mono font-bold text-terminal-fg">SNE Radar</h1>
                <p class="text-xs text-gray-500">Technical Analysis</p>
              </div>
            </router-link>
            
            <nav class="hidden md:flex items-center gap-6 ml-8">
              <router-link
                to="/dashboard"
                class="text-sm font-mono uppercase tracking-wider text-gray-400 hover:text-terminal-accent transition-colors"
                active-class="text-terminal-accent"
              >
                Dashboard
              </router-link>
              <router-link
                to="/chart"
                class="text-sm font-mono uppercase tracking-wider text-gray-400 hover:text-terminal-accent transition-colors"
                active-class="text-terminal-accent"
              >
                Charts
              </router-link>
              <router-link
                to="/analysis"
                class="text-sm font-mono uppercase tracking-wider text-gray-400 hover:text-terminal-accent transition-colors"
                active-class="text-terminal-accent"
              >
                Analysis
              </router-link>
            </nav>
          </div>
          
          <div class="flex items-center gap-4">
            <button
              v-if="!isConnected"
              @click="connectWallet"
              class="terminal-button primary sm"
            >
              Connect Wallet
            </button>
            <div v-else class="flex items-center gap-3">
              <div class="text-right">
                <div class="text-xs text-gray-500 font-mono">Tier</div>
                <div class="text-sm font-mono text-terminal-accent uppercase">{{ tier }}</div>
              </div>
              <div class="w-8 h-8 rounded-full border border-terminal-accent flex items-center justify-center">
                <span class="text-xs font-mono text-terminal-accent">
                  {{ address?.slice(0, 4) }}...{{ address?.slice(-4) }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    
    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-6 py-8">
      <slot />
    </main>
    
    <!-- Footer -->
    <footer class="border-t border-terminal-border mt-auto py-6">
      <div class="max-w-7xl mx-auto px-6">
        <div class="flex items-center justify-between text-sm text-gray-500 font-mono">
          <div>
            <span>SNE Radar v1.0.0</span>
            <span class="mx-2">•</span>
            <span>Powered by SNE Labs</span>
          </div>
          <div class="flex items-center gap-4">
            <a href="https://snelabs.space" target="_blank" class="hover:text-terminal-accent transition-colors">
              SNE Vault
            </a>
            <a href="https://pass.snelabs.space" target="_blank" class="hover:text-terminal-accent transition-colors">
              SNE Pass
            </a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useWallet } from '@/composables/useWallet'

const { address, isConnected, tier, connectWallet } = useWallet()
</script>

<style scoped>
.router-link-active {
  position: relative;
}

.router-link-active::after {
  content: '';
  position: absolute;
  bottom: -4px;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--terminal-accent);
  box-shadow: 0 0 10px rgba(0, 255, 0, 0.5);
}
</style>

// SNE-Scroll-Passport-main/SNE-Scroll-Passport-main/src/components/Layout.tsx
import type { ReactNode } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { Wallet } from 'lucide-react'
import WalletConnect from './Wallet/WalletConnect'
import GasTracker from './Gas/GasTracker'
import ModeSwitch from './Pro/ModeSwitch'

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  const location = useLocation()

  return (
    <div className="min-h-screen bg-scroll-darker text-white">
      {/* Header */}
      <header className="border-b border-scroll-dark/50 bg-scroll-dark/30 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-3">
          <div className="flex items-center justify-between">
            {/* Logo */}
            <Link to="/" className="flex items-center gap-2 group">
              <Wallet className="w-6 h-6 text-sne-neon group-hover:text-sne-cyan transition-colors" />
              <span className="text-xl font-bold font-mono">
                SNE <span className="text-sne-neon">Scroll</span> Pass
              </span>
            </Link>

            {/* Gas Tracker */}
            <div className="flex items-center gap-4">
              <GasTracker />
              <ModeSwitch />
              <WalletConnect />
            </div>
          </div>
        </div>
      </header>

      {/* Navigation */}
      <nav className="border-b border-scroll-dark/30 bg-scroll-dark/20">
        <div className="container mx-auto px-4">
          <div className="flex gap-1">
            <NavLink to="/" currentPath={location.pathname}>
              Dashboard
            </NavLink>
            <NavLink to="/transfer" currentPath={location.pathname}>
              Transfer
            </NavLink>
            <NavLink to="/spy" currentPath={location.pathname}>
              Spy Mode
            </NavLink>
            <NavLink to="/public" currentPath={location.pathname}>
              Public View
            </NavLink>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        {children}
      </main>

      {/* Footer */}
      <footer className="border-t border-scroll-dark/50 bg-scroll-dark/30 mt-auto py-6">
        <div className="container mx-auto px-4 text-center text-sm text-gray-400">
          <p>
            The unofficial official control panel for Scroll Network
          </p>
          <p className="mt-2">
            Powered by <span className="text-sne-neon font-mono">SNE Labs</span>
          </p>
        </div>
      </footer>
    </div>
  )
}

function NavLink({ to, currentPath, children }: { to: string; currentPath: string; children: ReactNode }) {
  const isActive = currentPath === to || (to !== '/' && currentPath.startsWith(to))
  
  return (
    <Link
      to={to}
      className={`px-4 py-3 text-sm font-medium transition-colors ${
        isActive
          ? 'text-sne-neon border-b-2 border-sne-neon'
          : 'text-gray-400 hover:text-white'
      }`}
    >
      {children}
    </Link>
  )
}
